# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a433ebdd07339745ad4c3c391f4f34858d393d6dcf7ab744d7a0b580df31d90aa9a09cb217771fbec3dd1cdbc7143670baa5f8e5ee464d0158ebf4518070ad23

test:
  secret_key_base: 5a59b94008c0733b13ddc23c6052e0bf14bea4e594fcf8a171624bef435067b0394eedbab7b9e5b1c9b91c38a9cb93af1015e37b454090cf3a40bcde1e791f47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
